# Generated by Django 3.2.18 on 2023-05-16 20:23

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(help_text='Максимальная длина 100 символов', max_length=100, unique=True, verbose_name='имя пользователя')),
                ('city', models.CharField(default='No city', help_text='Максимальная длина 100 символов', max_length=100, verbose_name='город (для кинологов)')),
                ('is_staff', models.BooleanField(default=False, verbose_name='сотрудник')),
                ('is_cynologist', models.BooleanField(default=False, verbose_name='кинолог')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='админ')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный пользователь')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
