# Generated by Django 3.2.18 on 2023-05-12 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Максимальная длина 80 символов', max_length=80, verbose_name='название')),
                ('description', models.TextField(help_text='Максимальная длина 100 символов', max_length=100, verbose_name='краткое описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('text', models.TextField(help_text='Содержание статьи', verbose_name='статья')),
                ('upload', models.ImageField(null=True, upload_to='uploads/', verbose_name='обложка')),
                ('size', models.IntegerField(help_text='1 - маленький, 3 - большой', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='размер')),
                ('activity', models.IntegerField(help_text='1 - низкая, 3 - высокая', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='активность')),
                ('cost', models.IntegerField(help_text='1 - низкая, 3 - высокая', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='стоимость содержания')),
                ('friendliness', models.IntegerField(help_text='1 - низкая, 3 - высокая', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='дружелюбность')),
                ('intellect', models.IntegerField(help_text='1 - низкий, 3 - высокий', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='интеллект')),
                ('noise', models.IntegerField(help_text='1 - низкий, 3 - высокий', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='шум')),
            ],
            options={
                'verbose_name': 'порода',
                'verbose_name_plural': 'породы',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_breed',
        ),
        migrations.AddField(
            model_name='article',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='обложка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.TextField(help_text='Максимальная длина 80 символов', max_length=80, verbose_name='название'),
        ),
    ]
