# Generated by Django 3.2.18 on 2023-04-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='обложка'),
        ),
    ]
