# Generated by Django 3.2.18 on 2023-05-14 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20230512_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='activity',
            field=models.IntegerField(choices=[(1, 'низкая'), (2, 'средняя'), (3, 'высокая')], help_text='1 - низкая, 3 - высокая', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='активность'),
        ),
    ]
