# Generated by Django 3.2.18 on 2023-05-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20230514_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='activity',
            field=models.IntegerField(blank=True, choices=[(1, 'Низкая'), (2, 'Средняя'), (3, 'Высокая')], null=True, verbose_name='активность'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='cost',
            field=models.IntegerField(blank=True, choices=[(1, 'Низкая'), (2, 'Средняя'), (3, 'Высокая')], null=True, verbose_name='стоимость содержания'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='friendliness',
            field=models.IntegerField(blank=True, choices=[(1, 'Низкая'), (2, 'Средняя'), (3, 'Высокая')], null=True, verbose_name='дружелюбность'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='intellect',
            field=models.IntegerField(blank=True, choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], null=True, verbose_name='интеллект'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='noise',
            field=models.IntegerField(blank=True, choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], null=True, verbose_name='шум'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.IntegerField(blank=True, choices=[(1, 'Маленький'), (2, 'Средний'), (3, 'Большой')], null=True, verbose_name='размер'),
        ),
    ]
